# Generated by Django 2.2.2 on 2020-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Registration_ID', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Semester', models.IntegerField()),
                ('Branch', models.TextField()),
            ],
        ),
    ]
