# Generated by Django 2.2.2 on 2020-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Registration_ID',
            field=models.BigIntegerField(),
        ),
    ]
