# Generated by Django 2.2.2 on 2020-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200422_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Registration_ID',
            field=models.FloatField(),
        ),
    ]
