# Generated by Django 2.2.2 on 2020-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200422_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(default='enter your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Registration_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Semester',
            field=models.CharField(max_length=20),
        ),
    ]
