# Generated by Django 2.2.2 on 2020-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200422_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Branch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
