# Generated by Django 2.2.2 on 2020-04-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200422_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
