# Generated by Django 2.2.2 on 2020-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('dob', models.DateField(max_length=8)),
                ('pno', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('highschool', models.CharField(max_length=20)),
                ('ssc', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('BTech', 'B.Tech'), ('MBA', 'MBA'), ('BPharma', 'B.Pharma'), ('DPharma', 'D.Pharma'), ('BBA', 'BBA'), ('Bcom', 'B.com')], default='BTech', max_length=10)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE BOARD', 'STATE BOARD')], default='CBSE', max_length=10)),
            ],
        ),
    ]
