# Generated by Django 2.2.2 on 2020-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='dob',
            field=models.DateField(help_text='mmddyyyy format', max_length=8),
        ),
    ]
