# Generated by Django 3.0.5 on 2020-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200425_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(help_text='mmddyyyy format', max_length=8)),
                ('pno', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=12)),
                ('course', models.CharField(choices=[('BTech', 'B.Tech'), ('MBA', 'MBA'), ('BPharma', 'B.Pharma'), ('DPharma', 'D.Pharma'), ('BBA', 'BBA'), ('Bcom', 'B.com')], default='BTech', max_length=20)),
            ],
        ),
    ]
