# Generated by Django 3.0.5 on 2020-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='male', max_length=20),
        ),
    ]
