# Generated by Django 2.2.2 on 2020-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200426_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(help_text='mmddyyyy format', max_length=8)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='male', max_length=20)),
                ('pno', models.CharField(max_length=100)),
                ('Registration_ID', models.CharField(help_text='Enter your Roll no.', max_length=20)),
                ('Semester', models.CharField(max_length=20)),
                ('Branch', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('BTech', 'B.Tech'), ('MBA', 'MBA'), ('BPharma', 'B.Pharma'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('BCA', 'BCA')], default='BTech', max_length=20)),
                ('cardholder', models.CharField(max_length=20)),
                ('cardno', models.CharField(max_length=12)),
                ('exmonth', models.CharField(max_length=2)),
                ('exyear', models.CharField(max_length=4)),
                ('CVV', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('BTech', 'B.Tech'), ('MBA', 'MBA'), ('BPharma', 'B.Pharma'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('BCA', 'BCA')], default='BTech', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('BTech', 'B.Tech'), ('MBA', 'MBA'), ('BPharma', 'B.Pharma'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('BCA', 'BCA')], default='BTech', max_length=20),
        ),
    ]
