# Generated by Django 3.0.5 on 2020-04-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='ssc',
        ),
    ]
